### ISSUE TITLE
/instance/connect/{instanceName} on v1.3.0 returns 401 Unauthorized 

### ISSUE THREAD

**Issue by eelco2k** [code-chat-br/whatsapp-api#101]
some endpoints give an 401 error:

```
curl -X 'GET' \
  'https://whatsapphost/instance/connect/device_8c60a480-cc06-4c87-97ae-b1152969cb42' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer mycorrectbearertoken'
```
Same error when using correct ApiKey Http Header.

logs give this error:
```
codechat_api     | [CodeChat]  1   -  Fri Jan 19 2024 19:52:20     ERROR   [JwtGuard]  [object]
codechat_api     | TypeError: (intermediate value)(intermediate value)(intermediate value) is not iterable
codechat_api     |     at JwtGuard.<anonymous> (/codechat/dist/src/guards/auth.guard.js:43:41)
codechat_api     |     at Generator.next (<anonymous>)
codechat_api     |     at /codechat/dist/src/guards/auth.guard.js:8:71
codechat_api     |     at new Promise (<anonymous>)
codechat_api     |     at __awaiter (/codechat/dist/src/guards/auth.guard.js:4:12)
codechat_api     |     at JwtGuard.canActivate (/codechat/dist/src/guards/auth.guard.js:28:16)
codechat_api     |     at /codechat/dist/src/app.module.js:113:134
codechat_api     |     at Generator.next (<anonymous>)
codechat_api     |     at /codechat/dist/src/app.module.js:31:71
codechat_api     |     at new Promise (<anonymous>)
codechat_api     |
codechat_api     | [CodeChat]  1   -  Fri Jan 19 2024 19:53:32     LOG   [LoggerMiddleware]  [object]
codechat_api     | {
codechat_api     |   originalUrl: '/instance/connect/device_8c60a480-cc06-4c87-97ae-b1152969cb42',
codechat_api     |   method: 'GET',
codechat_api     |   headers: '{"host":"localhost:8083","user-agent":"curl/7.86.0","accept":"application/json","authorization":"Bearer mycorrectbearer"}',
codechat_api     |   params: '{"instanceName":"device_8c60a480-cc06-4c87-97ae-b1152969cb42"}',
codechat_api     |   query: '{}',
codechat_api     |   body: '{}'
codechat_api     | }
codechat_api     |
codechat_api     | [CodeChat]  1   -  Fri Jan 19 2024 19:53:32     ERROR   [JwtGuard]  [object]
codechat_api     | { status: 401, error: 'Unauthorized', message: undefined }
codechat_api     |

```

**Comment by eelco2k** [comment]
never mind used wrong JWT token
