### ISSUE TITLE
Getting the error anonymously : Exception : TypeError: Cannot read properties of undefined (reading 'mediaMessage')

### ISSUE THREAD

**Issue by aravindanf22labs** [code-chat-br/whatsapp-api#126]

**Comment by aravindanf22labs** [comment]
Exception : TypeError: Cannot read properties of undefined (reading 'mediaMessage') : 
TypeError: Cannot read properties of undefined (reading 'mediaMessage')
    at SendMessageController.<anonymous> (/codechat/src/whatsapp/controllers/sendMessage.controller.js:34:71)
    at Generator.next (<anonymous>)
    at /codechat/src/whatsapp/controllers/sendMessage.controller.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/codechat/src/whatsapp/controllers/sendMessage.controller.js:4:12)
    at SendMessageController.sendMedia (/codechat/src/whatsapp/controllers/sendMessage.controller.js:25:16)
    at /codechat/src/utils/run-schedule.js:56:73
    at Generator.next (<anonymous>)
    at fulfilled (/codechat/src/utils/run-schedule.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by jrCleber** [comment]
The application attempted to access an instance that does not exist or is not connected.

**Comment by jrCleber** [comment]
[Reopen your issue here.](https://github.com/code-chat-br/whatsapp-api/issues/new?assignees=jrcleber&labels=bug%2Chelp+wanted&projects=&template=bug_report_en.yaml)
