### ISSUE TITLE
Receiving this error often Error: MessageRaw validation failed: source: `unknown` is not a valid enum value for path `source`

### ISSUE THREAD

**Issue by aravindanf22labs** [code-chat-br/whatsapp-api#127]
ERROR:  Error: MessageRaw validation failed: source: `unknown` is not a valid enum value for path `source`.
    at ValidationError.inspect (/codechat/node_modules/mongoose/lib/error/validation.js:50:26)
    at formatValue (node:internal/util/inspect:805:19)
    at inspect (node:internal/util/inspect:364:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2298:40)
    at formatWithOptions (node:internal/util/inspect:2160:10)
    at console.value (node:internal/console/constructor:342:14)
    at console.log (node:internal/console/constructor:379:61)
    at console.log (/codechat/node_modules/@sentry/utils/cjs/instrument/console.js:38:20)
    at MessageRepository.<anonymous> (/codechat/src/whatsapp/repository/message.repository.js:53:25)
    at Generator.throw (<anonymous>) {
  errors: {
    source: ValidatorError: `unknown` is not a valid enum value for path `source`.
        at validate (/codechat/node_modules/mongoose/lib/schemaType.js:1385:13)
        at SchemaType.doValidate (/codechat/node_modules/mongoose/lib/schemaType.js:1369:7)
        at /codechat/node_modules/mongoose/lib/document.js:3042:18
        at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
      properties: [Object],
      kind: 'enum',
      path: 'source',
      value: 'unknown',
      reason: undefined,
      [Symbol(mongoose#validatorError)]: true
    }
  },
  _message: 'MessageRaw validation failed'

**Comment by jrCleber** [comment]
Not enough context to understand your issue.
[Reopen your issue here.](https://github.com/code-chat-br/whatsapp-api/issues/new?assignees=jrcleber&labels=bug%2Chelp+wanted&projects=&template=bug_report_en.yaml)
