### ISSUE TITLE
Erro ao recuperar sticker enviados pelo whatsapp web

### ISSUE THREAD

**Issue by cleitinif** [code-chat-br/whatsapp-api#147]
### Pesquisei problemas semelhantes no [GitHub](https://github.com/code-chat-br/whatsapp-api/issues) e não encontrei nenhum.

- [X] Sim

### Quais passos para chegar ao problema?

Configurei uma instance, conectei meu whatsapp e configurei um endpoint para receber os webhooks de todos os tipos de eventos.

Enviei uma mensagem de sticker para um número qualquer através do whatsapp web e recebi o webhook do messageType `stickerMessage` 

### Descreva o que você esperava que acontecesse.

Esperava que o conteúdo do `data.content.url` fosse algo como `https://mmg.whatsapp.net/v/v/t62.1345-24/2634383_321_n.enc?ccb=11-4&oh=01_Q5AaIOB3bsv69qzeZasMPzsR5926OA6w&oe=66F085A2&_nc_sid=5e043&mms3=true`, pois é assim que vem nos eventos de sticker enviados pelo celular.

### Explique o que realmente acontece quando você segue os passos acima.

Através do whatsapp web ele vem como `https://web.whatsapp.net`, faltando informações para recuperar a media pelo endpoint `/chat/retrieverMediaMessage`

### Insira o número da sua versão que está na propriedade `version` do **package.json**.

1.3.2

### Se possível, adicione capturas de tela ou vídeos que ilustrem o problema.
Isso pode ser extremamente útil para entender melhor o problema.

Retorno do endpoint utilizando o ID da mensagem enviada pelo whatsapp-web
![image](https://github.com/user-attachments/assets/ce0f2b13-2f00-4310-add1-f47c2056e955)

### O ambiente no qual a aplicação está em execução

Docker

### Por favor, anexe os logs que possam estar relacionados ao problema.
Se os logs contiverem informações sensíveis, considere enviá-los de forma privada para um dos mantenedores do projeto.

```log
[CodeChat]  1   -  Fri Aug 23 2024 22:35:59     ERROR   [WAStartupService]  [1:cleiton]   
AxiosError: getaddrinfo ENOTFOUND web.whatsapp.net
    at AxiosError.from (file:///codechat/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (file:///codechat/node_modules/axios/lib/adapters/http.js:620:25)
    at RedirectableRequest.emit (node:events:519:28)
    at eventHandlers.<computed> (/codechat/node_modules/follow-redirects/index.js:38:24)
    at ClientRequest.emit (node:events:519:28)
    at emitErrorEvent (node:_http_client:108:11)
    at TLSSocket.socketErrorListener (node:_http_client:511:5)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (file:///codechat/node_modules/axios/lib/core/Axios.js:45:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getHttpStream (/codechat/node_modules/@whiskeysockets/baileys/lib/Utils/messages-media.js:317:21)
    at async downloadEncryptedContent (/codechat/node_modules/@whiskeysockets/baileys/lib/Utils/messages-media.js:450:21)
    at async downloadMsg (/codechat/node_modules/@whiskeysockets/baileys/lib/Utils/messages.js:747:24)
    at async downloadMediaMessage (/codechat/node_modules/@whiskeysockets/baileys/lib/Utils/messages.js:707:20) {
  hostname: 'web.whatsapp.net',
  syscall: 'getaddrinfo',
  code: 'ENOTFOUND',
  errno: -3008,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http', 'fetch' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: Infinity,
    maxBodyLength: Infinity,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': undefined,
      Origin: 'https://web.whatsapp.com',
      'User-Agent': 'axios/1.7.4',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    responseType: 'stream',
    method: 'get',
    url: 'https://web.whatsapp.net',
    data: undefined
  },
  request: <ref *1> Writable {
    _events: {
      close: undefined,
      error: [Function: handleRequestError],
      prefinish: undefined,
      finish: undefined,
      drain: undefined,
      response: [Function: handleResponse],
      socket: [Function: handleRequestSocket]
    },
    _writableState: WritableState {
      highWaterMark: 16384,
      length: 0,
      corked: 0,
      onwrite: [Function: bound onwrite],
      writelen: 0,
      bufferedIndex: 0,
      pendingcb: 0,
      [Symbol(kState)]: 17580812,
      [Symbol(kBufferedValue)]: null
    },
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'https:',
      path: '/',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: 'web.whatsapp.net',
      port: '',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _eventsCount: 3,
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET / HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Origin: https://web.whatsapp.com\r\n' +
        'User-Agent: axios/1.7.4\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: web.whatsapp.net\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'web.whatsapp.net',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://web.whatsapp.net/',
    [Symbol(shapeMode)]: true,
    [Symbol(kCapture)]: false
  },
  cause: Error: getaddrinfo ENOTFOUND web.whatsapp.net
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'web.whatsapp.net'
  }
}
```

### Inclua aqui qualquer outra informação que você ache que possa ser útil para entender ou resolver o bug.

Conteúdo de um evento de sticker enviado pelo whatsapp-web

```
{
  keyId: '...',
  messageType: 'stickerMessage',
  content: StickerMessage {
    url: 'https://web.whatsapp.net',
    fileSha256: Uint8Array(32) [],
    fileEncSha256: Uint8Array(32) [ ],
    mediaKey: Uint8Array(32) [],
    mimetype: 'image/webp',
    directPath: '/v/t62.15575-24/21229778_767316098751676_810392057281....,
    isAnimated: true,
    contextInfo: ContextInfo {
      mentionedJid: [],
      groupMentions: [],
      disappearingMode: [DisappearingMode]
    },
    stickerSentTs: Long { low: -2124720123, high: 401, unsigned: false }
  }
}
```

Conteúdo de um evento de sticker enviado pelo celular

```
{
  keyId: '...',
  messageType: 'stickerMessage',
  content: StickerMessage {
    url: 'https://mmg.whatsapp.net/v/t62.15575-24/30915988_836446238...',
    fileSha256: Uint8Array(32) [ ],
    fileEncSha256: Uint8Array(32) [],
    mediaKey: Uint8Array(32) [],
    mimetype: 'image/webp',
    directPath: '/v/t62.15575-24/30915988_836446238632250_2133...,
    fileLength: Long { low: 126634, high: 0, unsigned: true },
    mediaKeyTimestamp: Long { low: 1724452770, high: 0, unsigned: false },
    firstFrameLength: 6260,
    firstFrameSidecar: Uint8Array(10) [],
    isAnimated: true,
    stickerSentTs: Long { low: -2124082517, high: 401, unsigned: false },
    isAvatar: false,
    isAiSticker: false,
    isLottie: false
  }
}
```

**Comment by jrCleber** [comment]
Acabei de fazer alguns testes aqui com stickers animados e estáticos. Não obtive erro algum.

**Sticker:**
![image](https://github.com/user-attachments/assets/cf81fb27-4e9a-43d6-9a6c-915f604a11af)

**Recuperação do Sticker:**
![image](https://github.com/user-attachments/assets/e1370940-0a89-4c2b-8af7-69cab947caf0)

**Comment by jrCleber** [comment]
Recomendações:

- Atualizar o código;
- Refazer as migrations no banco;

Caso o erro persista, me encaminha esse sticker no grupo e me marca.

**Comment by RianBrenoPolonini** [comment]
Boa tarde, @cleitinif e @jrCleber !

Já passei por esse problema também, aparentemente ele é um problema da dependência do [Baileys](https://github.com/WhiskeySockets/Baileys), consegui fazer uma solução baseada numa issue de lé, segue ela:
[[BUG] Unable to download SAVED sticker from whatsapp AXIOS error](https://github.com/WhiskeySockets/Baileys/issues/465#issuecomment-1870724057)
